object Versions{
    const val accompanist_version = "0.30.1"
    const val compose_NavVersion = "2.5.0"
    const val activity_version = "1.4.0"
    const val constraint_version = "1.0.0"
    const val compose_version = "1.4.0-rc01"
    const val lifecycle_version = "2.6.0"
    const val arch_version = "2.2.0"
    const val destinations_version = "1.8.36-beta"
    const val kotlin_version = "1.9.0"
    const val coroutines_version = "1.6.4"
    const val hilt_version = "2.44"
    const val hiltComposeNavigation = "1.0.0"
    const val room_version = "2.5.1"
}